### ISSUE TITLE
Hard coded first slash removel

### ISSUE THREAD

**Issue by fishrockz** [pelican-plugins/image-process#30]
I use gitlab pages to host my blog

my pages start from

user.gitlab.io/projectname

so i set SITEURL to "projectname" in the publishconf.py

and i have relative paths in my rst eg

.. image:: media/post/file.jpg

this brakes image_process as it looks for files called `edia/post/file.jpg`

i have a fix for this https://github.com/fishrockz/image_process/commit/7a365873d7fd4134e47b48c9493e346a4668768b but im not sure its the best way to do it.

would you like me to create a PR or is there a better way to confige image_process to avoid this?

**Comment by kernc** [comment]
@fishrockz Can you check whether this is still an issue with the current master? Just might have been touched/fixed by #27.

**Comment by kernc** [comment]
Indeed, seems like fixed in https://github.com/pelican-plugins/image-process/commit/56ae9acaa572e43ed4048bb8c7712f8fa40bafbe. If not, reopen.
