### ISSUE TITLE
click through to full image

### ISSUE THREAD

**Issue by fishrockz** [pelican-plugins/image-process#31]
I can see that not every one want to host full size images but i would like users/views of my blog to be able to click through to the original.

Have i missed something in the config or is this much harder to do?

If its do able i would be happy to help but im not sure what the maintainers think is the best way to do this? if a doc fix is what is needed i am happy to help with that or to add some code.. but dont want to duplicate effort if some already knows how to do it

**Comment by kernc** [comment]
The way I do it in markdown is:
```markdown
[![some photo][photo_link]{:.image-process-photos}][photo_link]

[photo_link]: {static}/images/photo.jpg
```

This adds a processed photo `<img>` wrapped in a `<a>` link pointing to the original resource.

It depends on [Markdown Attribute Lists extension](https://python-markdown.github.io/extensions/attr_list/), i.e.:
```py
MARKDOWN = dict(
    ...
    extensions=[
        ...
        'markdown.extensions.attr_list',  # <-- this
```
and on #27 (just merged).

The same can be done in raw HTML and this has no extra dependencies:
```html
<a href="/images/photo.jpg"><img class="process-image-photos" src="/images/photo.jpg"></a>

**Comment by patrickfournier** [comment]
In restructuredText, one would use the `:target:` option on the `image::` of `figure::` directive.
