### ISSUE TITLE
Stepping down as maintainer / pypi package admin

### ISSUE THREAD

**Issue by Ecno92** [pelican-plugins/image-process#32]
Hello everybody, 

I would like to announce my intentions to step down as a maintainer of image_process and the related [pypi repository](https://pypi.org/project/pelican-image-process/).
The reason for this is that I decided to stop using all pelican plugins and the fact that I do not feel very comfortable with the code of this project.

I see that some other people are showing some real interest in this project. So I hereby would encourage you to step up as a potential maintainer of the project so that you can push some new releases. :+1: 

@patrickfournier Can you let me know if you want to take over the pypi repository? Or maybe you can suggest somebody?

**Comment by patrickfournier** [comment]
Hi @Ecno92 ,

Thank you for your time as a maintainer of the project and your help in improving image_process. 

If anyone is interested in maintaining this repo and the pypi repository, please say so. Otherwise, if nobody else shows interest, I can take over the pypi repository too. Just brief me about what it involves.

Patrick

**Comment by justinmayer** [comment]
Hi Therry. As Pelican’s primary maintainer, I saw your announcement and thought I would reach out. 👋

Have you seen the new [Pelican Plugins](https://github.com/pelican-plugins) organization? We have begun a gradual process of migrating plugins there, both from the [legacy monolithic repository](https://github.com/getpelican/pelican-plugins#pelican-plugins) as well as from individual repositories such as this one. Under the auspices of the new organization, the broader community (including @patrickfournier, of course) could pick up the mantle and continue the plugin’s enhancement and maintenance. We have already migrated several plugin repositories over to the new organization, all of which have also been converted to the new namespace plugin format supported by Pelican 4.5+.

Assuming you find it amenable, I would be happy to help out with this transition. What do you think? ✨

**Comment by Ecno92** [comment]
If @patrickfournier is up for it I'll assist to transfer the rights of the [PyPi project](https://pypi.org/project/pelican-image-process/). :+1:

**Comment by justinmayer** [comment]
If the benefits I mentioned above seem worthwhile, feel free to add me to this repository with admin role access via the [respective settings](https://github.com/whiskyechobravo/image_process/settings/access). I would be happy to put in the time and help move the project forward. 🚀

**Comment by patrickfournier** [comment]
Ok let's move this repository to the Pelican Plugins org (nice logo by the way!). 

@Ecno92  I gave you admin rights in case you need them for the transition.
@justinmayer I am adding you to this repository as an admin. If you would like to manage the PyPi project too, please do!

Thanks!

**Comment by justinmayer** [comment]
Thank you, Patrick! I moved the repository to the new organization. Thanks also for the PyPI invitation as well. Would you be so kind as to add the [`pelicanteam`](https://pypi.org/user/pelicanteam/) account (with "Owner" role) to the Image Process project on PyPI?

Credit for the [sharp-looking logo](https://blog.getpelican.com/pages/gratitude.html) must go to @hyperking. I agree he did a fantastic job. 😁

**Comment by Ecno92** [comment]
@justinmayer I've invited pelicanteam to the PyPi project.

**Comment by MinchinWeb** [comment]
I was just going to second the Pelican Plugin organization, but I see I'm late to the party! I'm slowly moving my plugins over there too, and I hope that eventually it will make maintaining the plugins simpler. I will try and make sure my fork (of this plugin) is completely merged in here. @Ecno92, thanks for all you've done with this to date!

**Comment by Ecno92** [comment]
Thank you very much all. I'll be closing this issue as it seems like everything has been migrated. 
If no further actions are required then I will remove my maintainer access in the beginning of 2021.
