### ISSUE TITLE
Remove stale branches

### ISSUE THREAD

**Issue by kdeldycke** [pelican-plugins/image-process#35]
I spotted a couple of staled branches that I propose for deletion:
* [x] `united-community-efforts` => just a saving point used during the transition. Can be safely deleted.
* [x] `release` => Old readme fixes already merged.
* [x] `pelican-plugins-pypi-move-warning` => No longer necessary now that we migrated and reused the old repository.

You can delete branches at: https://github.com/pelican-plugins/image-process/branches

* [x] Oh, and while you're at it, maybe we can rename `master` to `main` (see #34)! :)

**Comment by kernc** [comment]
Let's split the effort: I deleted the stale branches, you do the renaming. I'm not on the overly sensitive side.

![Q: So did you do anything interesting last weekend?  A: Why are you attacking me? :sob:](https://user-images.githubusercontent.com/684364/100638695-9bcab080-3334-11eb-8458-75539fd585ee.png)

**Comment by kdeldycke** [comment]
Aha thanks for removing stale branches!

But I just realized I don't have the necessary rights to rename branches on that repository! 😅 Do you? 😬

**Comment by justinmayer** [comment]
Will change the primary branch name now…

**Comment by justinmayer** [comment]
Primary branch is now `main`. GitHub announced plans to provide a [seamless method to do this](https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories-) for existing repositories "by the end of the year", so hopefully we can avoid this dance soon.

Reference: https://jarv.is/notes/github-rename-master/

**Comment by kdeldycke** [comment]
Thanks @justinmayer for renaming the branch! I reopened my packaging PR at #38.
