### ISSUE TITLE
Global off switch

### ISSUE THREAD

**Issue by MinchinWeb** [pelican-plugins/image-process#52]
The plugin can take some time to run, and so for local development, i can be helpful to turn the plugin off. Previously, I'd do this by having differing lists of plugins in `pelicanconf.py` (for local development) and `publishconf.py` (for deployment), however with namespace plugins, I'm trying to move away from maintaining a list of plugins in either place.

So I would be helpful to have a "master" setting (like `IMAGE_PROCESS_ACTIVE`) that I could set to False and just turn it off for local development.

**Comment by kernc** [comment]
Maybe this works:
```py
# publishconf.py:

IMAGE_PROCESS = {}
```
?

**Comment by MinchinWeb** [comment]
> Maybe this works:
> 
> ```python
> # publishconf.py:
> 
> IMAGE_PROCESS = {}
> ```
> 
> ?

That seems to work!
